export const Routes = {
  home: "/",
  haberler: "/",
  tanitim: "/tanitim",
  isletmeler: "/isletmeler",
  yerelPazar: "/yerelpazar",
  ulasim: "/ulasim",
  galeri: "/galeri",
  about: "/about",
  kullanimKosullari: "/kullanımkosulları",
  loginPage: "/logrinpage",
  signUp: "/signup",
  pazarurunekle: "/yerelpazar/pazarurunekle",
  baharatlar: "/yerelpazar/baharatlar",
  baklagiller: "/yerelpazar/baklagiller",
  elisleri: "/yerelpazar/elisleri",
  hayvanlar: "/yerelpazar/hayvanlar",
  ikinciel: "/yerelpazar/ikinciel",
  insaatmalzemeleri: "/yerelpazar/insaatmalzemeleri",
  meyvesebze: "/yerelpazar/meyvesebze",
  mobilyalar: "/yerelpazar/mobilyalar",
  suturunleri: "/yerelpazar/suturunleri",
  minibusseferekle: "/ulasim/busseferekle",
  paylasimliarabaekle: "/ulasim/arabaekle",
  minibus: "/ulasim/minibus",
  paylasimliaraba: "/ulasim/paylasimliaraba",
  haberekle: "/haberekle",
};
export default Routes;
